{"name": "test_add[get_datas_add1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -2 == 0\n  +-2\n  -0", "trace": "self = <pytest_combat.testcases.test_calcu_new.TestCalc object at 0x000001E3CCD765B0>, get_calc = <pytest_combat.api.calculator.Calculator object at 0x000001E3CCD76040>\nget_datas_add = [-1, -1, 0], all_start = None\n\n    @pytest.mark.first\n    def test_add(self,get_calc,get_datas_add,all_start):\n        result = None\n        try:\n            #用fixture方法名返回计算器实例并调用计算器中的方法add\n            result = get_calc.add(get_datas_add[0], get_datas_add[1])\n            if isinstance(result,float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n    \n>       assert result == get_datas_add[2]\nE       assert -2 == 0\nE         +-2\nE         -0\n\ntest_calcu_new.py:18: AssertionError"}, "parameters": [{"name": "get_datas_add", "value": "[-1, -1, 0]"}], "start": 1622384497465, "stop": 1622384497465, "uuid": "51b97a67-dfe6-4288-825d-40f412840a84", "historyId": "9df2588b239f4146fb34a708629e7fdd", "testCaseId": "9117aa56cd4623e5c949e74de2331c8a", "fullName": "pytest_combat.testcases.test_calcu_new.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=0)"}, {"name": "tag", "value": "first"}, {"name": "parentSuite", "value": "pytest_combat.testcases"}, {"name": "suite", "value": "test_calcu_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-EP4FUOH"}, {"name": "thread", "value": "11752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_combat.testcases.test_calcu_new"}]}