{"name": "test_add[get_datas_add4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'a'\n  +None\n  -'a'", "trace": "self = <pytest_combat.testcases.test_calcu_new.TestCalc object at 0x000001E3CCD76520>, get_calc = <pytest_combat.api.calculator.Calculator object at 0x000001E3CCD76040>\nget_datas_add = ['', 5, 'a'], all_start = None\n\n    @pytest.mark.first\n    def test_add(self,get_calc,get_datas_add,all_start):\n        result = None\n        try:\n            #用fixture方法名返回计算器实例并调用计算器中的方法add\n            result = get_calc.add(get_datas_add[0], get_datas_add[1])\n            if isinstance(result,float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n    \n>       assert result == get_datas_add[2]\nE       AssertionError: assert None == 'a'\nE         +None\nE         -'a'\n\ntest_calcu_new.py:18: AssertionError"}, "parameters": [{"name": "get_datas_add", "value": "['', 5, 'a']"}], "start": 1622384497703, "stop": 1622384497704, "uuid": "1388bc15-f764-421a-9bd4-ef8b155428bc", "historyId": "e2cdf6688d5c256af0e949a190d6d5f2", "testCaseId": "9117aa56cd4623e5c949e74de2331c8a", "fullName": "pytest_combat.testcases.test_calcu_new.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=0)"}, {"name": "tag", "value": "first"}, {"name": "parentSuite", "value": "pytest_combat.testcases"}, {"name": "suite", "value": "test_calcu_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-EP4FUOH"}, {"name": "thread", "value": "11752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_combat.testcases.test_calcu_new"}]}