{"name": "test_add[minus]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -2 == 0\n  +-2\n  -0", "trace": "self = <pytest_combat.testcases.test_calcu_new.TestCalc object at 0x0000019E231EF910>, get_calc = <pytest_combat.api.calculator.Calculator object at 0x0000019E231EFD30>\nget_datas = [-1, -1, 0]\n\n    def test_add(self,get_calc,get_datas):\n        result = None\n        try:\n            #用fixture方法名返回计算器实例并调用计算器中的方法add\n            result = get_calc.add(get_datas[0], get_datas[1])\n            if isinstance(result,float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n    \n    \n>       assert result == get_datas[2]\nE       assert -2 == 0\nE         +-2\nE         -0\n\ntest_calcu_new.py:19: AssertionError"}, "parameters": [{"name": "get_datas", "value": "[-1, -1, 0]"}], "start": 1622350694247, "stop": 1622350694247, "uuid": "a8d69081-0962-4218-9366-a4eb16d27e8a", "historyId": "3a44fe1f1d21650c8ba8e95837d3bed3", "testCaseId": "9117aa56cd4623e5c949e74de2331c8a", "fullName": "pytest_combat.testcases.test_calcu_new.TestCalc#test_add", "labels": [{"name": "parentSuite", "value": "pytest_combat.testcases"}, {"name": "suite", "value": "test_calcu_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-EP4FUOH"}, {"name": "thread", "value": "2032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_combat.testcases.test_calcu_new"}]}